source 'https://rubygems.org'

#ruby '2.7.1'

gem 'minitest'
gem 'rake'
gem 'rubocop'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-reloader'
gem 'activesupport'
gem 'activerecord'
gem 'pg'
gem 'http'
gem 'httparty'
gem 'ruby-openai'
gem 'dotenv'
gem 'bcrypt'
gem 'sinatra-flash'
gem 'rufus-scheduler'
gem 'pastel'